# Generated by Django 3.2.8 on 2021-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'camping',
            },
        ),
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikename', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('difficulty', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hiking',
            },
        ),
    ]
