# Generated by Django 3.2.9 on 2021-11-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventurepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiking',
            name='bathroom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hiking',
            name='elevationgain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiking',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hiking',
            name='potablewater',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hiking',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
