# Generated by Django 3.2.8 on 2021-12-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventurepages', '0002_auto_20211119_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camping',
            new_name='Camp',
        ),
        migrations.RenameModel(
            old_name='Hiking',
            new_name='Hike',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='potablewater',
            new_name='portablewater',
        ),
    ]
