# Generated by Django 3.2.8 on 2021-12-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventurepages', '0003_auto_20211211_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
